Areas/Admin/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using truyenchu.Components;
using truyenchu.Data;
using truyenchu.Models;
using truyenchu.Utilities;

namespace truyenchu.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    [Route("manage-author/[action]")]
    public class AuthorController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ILogger<AuthorController> _logger;

        public AuthorController(AppDbContext context, ILogger<AuthorController> logger)
        {
            _context = context;
            _logger = logger;
        }

        [TempData]
        public string StatusMessage { get; set; }

        // GET: Author
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAuthors(string searchStr, int pageNumber = 1)
        {
            if (_context.Authors == null)
                return NotFound();

            List<Author> authors = new List<Author>();
            var qr = _context.Authors.OrderByDescending(x => x.DateUpdated);

            if (!string.IsNullOrEmpty(searchStr))
            {
                searchStr = AppUtilities.GenerateSlug(searchStr);
                // find by slug
                authors = await qr.Where(a => a.AuthorSlug.Contains(searchStr))
                                    .ToListAsync();
            }
            else
                authors = await qr.ToListAsync();

            var result = Pagination.PagedResults(authors, pageNumber, Const.AUTHORS_FOUND_PER_PAGE);

            return Json(result);
        }

        // GET: Author/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuthorName")] Author author)
        {
            ModelState.Remove(nameof(author.AuthorSlug));
            if (!ModelState.IsValid)
                return View();

            author.AuthorSlug = GenerateAuthorSlug(author);
            author.DateCreated = DateTime.Now;
            author.DateUpdated = DateTime.Now;

            _context.Add(author);
            await _context.SaveChangesAsync();
            StatusMessage = "Thêm tác giả thành công";
            return RedirectToAction(nameof(Index));
        }

        // GET: Author/Edit/5
        [Route("{id?}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost(Name = "EditAuthor")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm(Name = "AuthorId")] int id, [Bind("AuthorId,AuthorName")] Author author)
        {
            if (id != author.AuthorId) return NotFound();

            ModelState.Remove(nameof(author.AuthorSlug));
            if (!ModelState.IsValid) return View(author);

            author.AuthorSlug = GenerateAuthorSlug(author);
            author.DateUpdated = DateTime.Now;

            try
            {
                _context.Update(author);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AuthorExists(author.AuthorId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            StatusMessage = "Cập nhật tác giả thành công";
            return RedirectToAction(nameof(Index));

        }

        [Route("{id?}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.AuthorId == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Author/Delete/5
        [HttpPost(Name = "DeleteAuthor")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int authorId)
        {
            if (_context.Authors == null)
            {
                return Problem("Entity set 'AppDbContext.Authors'  is null.");
            }
            var author = await _context.Authors.FindAsync(authorId);
            if (author != null)
            {
                _context.Authors.Remove(author);
            }

            await _context.SaveChangesAsync();

            StatusMessage = "Xóa tác giả thành công";
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
            return (_context.Authors?.Any(e => e.AuthorId == id)).GetValueOrDefault();
        }

        // abc-xyz ==> abc-xyz1, abc-xyz2,...
        private string GenerateAuthorSlug(Author author)
        {
            var counter = 1;
            var prefix = "";
            var slug = AppUtilities.GenerateSlug(author.AuthorName);
            while (_context.Authors.Any(x => x.AuthorSlug == slug + prefix && x.AuthorId != author.AuthorId))
            {
                prefix = "-" + counter.ToString();
                counter++;
            }
            return slug + prefix;
        }
    }
}

Areas/Admin/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using ImageProcessor;
using ImageProcessor.Imaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using truyenchu.Areas.Admin.Model;
using truyenchu.Data;
using truyenchu.Models;
using truyenchu.Service;
using truyenchu.Utilities;

namespace truyenchu.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    [Route("manage-story/[action]")]
    public class StoryController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ILogger<StoryController> _logger;
        private readonly StoryService _storyService;
        public StoryController(AppDbContext context, ILogger<StoryController> logger, StoryService storyService)
        {
            _context = context;
            _logger = logger;
            _storyService = storyService;
        }

        [TempData]
        public string StatusMessage { get; set; }

        // GET: Story
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetStories(string searchStr, int pageNumber = 1)
        {
            if (_context.Stories == null)
                return NotFound();

            var qr = _context.Stories
                                    .Include(x => x.Author)
                                    .Include(x => x.Photo)
                                    .Select(s => new
                                    {
                                        s.StoryId,
                                        s.Photo.FileName,
                                        s.Author.AuthorName,
                                        s.StoryName,
                                        s.StorySlug,
                                        s.StoryState,
                                        s.ViewCount,
                                        s.LatestChapterOrder,
                                        s.DateUpdated,
                                        s.Published
                                    })
                                    .OrderByDescending(x => x.DateUpdated)
                                    .AsQueryable();

            dynamic vm;
            if (!string.IsNullOrEmpty(searchStr))
            {
                searchStr = AppUtilities.GenerateSlug(searchStr);
                // find by slug
                vm = await qr.Where(a => a.StorySlug.Contains(searchStr)).ToListAsync();

            }
            else
                vm = await qr.ToListAsync();

            var result = Pagination.PagedResults(vm, pageNumber, Const.STORIES_PER_PAGE_ADMIN);

            return Json(result);
        }

        // api 
        [HttpGet]
        public async Task<IActionResult> GetAuthor(string query)
        {
            if (_context.Stories == null)
                return NotFound();

            if (!string.IsNullOrEmpty(query))
                query = AppUtilities.GenerateSlug(query);

            var authors = await _context.Authors.Where(x => x.AuthorSlug.Contains(query)).Select(x => new { x.AuthorId, x.AuthorName }).ToListAsync();
            return Json(authors);
        }
        // GET: Story/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Stories == null)
            {
                return NotFound();
            }

            var story = await _context.Stories
                .Include(s => s.Author)
                .Include(s => s.Photo)
                .FirstOrDefaultAsync(m => m.StoryId == id);
            if (story == null)
            {
                return NotFound();
            }

            return View(story);
        }

        // GET: Story/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.MultiSelectItem = await GetMultiSelectList();
            return View();
        }

        // POST: Story/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StoryName,AuthorId,Description,StorySource, CategoryIds")] CreateViewModel story, IFormFile? file)
        {
            ViewBag.MultiSelectItem = await GetMultiSelectList();

            if (story.AuthorId == 0)
            {
                ModelState.Remove(nameof(story.AuthorId));
                ModelState.AddModelError(nameof(story.AuthorId), "Phải chọn tác giả");
                return View(story);
            }
            if (ModelState.IsValid)
            {
                var photo = new StoryPhoto();
                photo.FileName = file != null ? AppUtilities.UploadPhoto(file) : Const.STORY_THUMB_NO_IMAGE;
                story.Photo = photo;
                _context.StoryPhotos.Add(photo);


                story.StorySlug = GenerateStorySlug(story.StoryName);
                story.LatestChapterOrder = 0;
                story.DateCreated = DateTime.Now;
                story.DateUpdated = DateTime.Now;
                story.ViewCount = 0;
                story.StoryState = false;

                foreach (int cateId in story.CategoryIds)
                {
                    _context.Add(new StoryCategory() { CategoryId = cateId, Story = story });
                }

                _context.Add(story);
                await _context.SaveChangesAsync();

                StatusMessage = "Thêm truyện mới thành công";
                return RedirectToAction(nameof(Index));
            }

            return View(story);
        }

        // GET: Story/Edit/5
        [Route("{id?}")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.Stories == null)
            {
                return NotFound();
            }

            var story = await _context.Stories.Include(x => x.StoryCategory).Include(x => x.Author).Include(x => x.Photo).FirstOrDefaultAsync(x => x.StoryId == id);
            if (story == null)
            {
                return NotFound();
            }

            var categoryIds = story.StoryCategory.Select(x => x.CategoryId).ToArray();

            var vm = new CreateViewModel(story, categoryIds);

            ViewBag.MultiSelectItem = await GetMultiSelectList();
            return View(vm);
        }

        // POST: Story/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost(Name = "EditStory")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm(Name = "StoryId")] int id, [Bind("StoryId,StoryName,AuthorId,Description,StorySource,StoryState,CategoryIds")] CreateViewModel model, IFormFile? file)
        {
            if (id != model.StoryId)
                return NotFound();


            var story = await _context.Stories
                                            .Include(x => x.Author)
                                            .Include(x => x.Photo)
                                            .Include(x => x.StoryCategory)
                                            .FirstOrDefaultAsync(x => x.StoryId == id);
            if (story == null)
                return NotFound();

            var categoryIds = story.StoryCategory.Select(x => x.CategoryId).ToArray();
            var vm = new CreateViewModel(story, categoryIds);
            ViewBag.MultiSelectItem = await GetMultiSelectList();
            if (model.AuthorId == 0)
            {
                ModelState.Remove(nameof(model.AuthorId));
                ModelState.AddModelError(nameof(model.AuthorId), "Phải chọn tác giả");
                return View(vm);
            }

            if (ModelState.IsValid)
            {
                try
                {

                    story.StoryName = model.StoryName;
                    story.StorySource = model.StorySource;
                    story.AuthorId = model.AuthorId;
                    story.Description = model.Description;
                    story.StoryState = model.StoryState;
                    story.DateUpdated = DateTime.Now;

                    if (file != null)
                    {
                        var photo = await _context.StoryPhotos.FindAsync(story.PhotoId);
                        // Xóa img cũ
                        if (photo != null && photo.FileName != Const.STORY_THUMB_NO_IMAGE)
                        {
                            _context.Remove(photo);
                            AppUtilities.DeletePhoto(photo.FileName);
                        }

                        // Upload mới
                        var newPhoto = new StoryPhoto()
                        {
                            FileName = AppUtilities.UploadPhoto(file)
                        };
                        story.Photo = newPhoto;
                        _context.StoryPhotos.Add(newPhoto);
                    }

                    var oldCateIds = story.StoryCategory.Select(x => x.CategoryId);
                    var newCateIds = model.CategoryIds;

                    var removeCates = story.StoryCategory.Where(x => !newCateIds.Contains(x.CategoryId)).ToList();
                    var addCates = newCateIds.Where(x => !oldCateIds.Contains(x)).ToList();

                    _context.StoryCategories.RemoveRange(removeCates);
                    addCates.ForEach(cate =>
                    {
                        _context.StoryCategories.Add(new StoryCategory()
                        {
                            Story = story,

Views/Shared/_AdminLayout.cshtml
@{
    var actionPage = ViewData["ActivePage"] as string;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/contents/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/contents/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/contents/favicon/favicon-16x16.png">
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />

    <link href="~/lib/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/lib/typeahead/style.css" rel="stylesheet">
    <link href="~/css/main.admin.min.css" rel="stylesheet">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    

    @* AutoComplete *@
    <script src="~/lib/typeahead/bloodhound.min.js"></script>
    <script src="~/lib/typeahead/typeahead.bundle.min.js"></script>
    <script src="~/lib/typeahead/typeahead.jquery.min.js"></script>
    
    @* Sumernote *@
    <link rel="stylesheet" href="~/lib/summernote/summernote-lite.min.css" />
    <script src="~/lib/summernote/summernote-lite.min.js"></script>


    @* My js *@
    <script src="~/js/collapse.admin.js"></script>
    <script src="~/js/paging.js"></script>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-area="Admin" asp-controller="Admin" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="bi bi-book-half fs-3"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Truyện chữ</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link"  asp-area="Admin" asp-controller="Admin" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Quản lý truyện
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#collapseTwo" data-bs-toggle="collapse"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Quản lý danh mục</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item @ManageNavPages.AuthorNavClass(actionPage)" asp-area="Admin" asp-controller="Author" asp-action="Index" >
                            <i class="fas fa-user-edit fa-lg"></i>
                            Tác giả
                        </a>
                        <a class="collapse-item @ManageNavPages.CategoryNavClass(actionPage)" asp-area="Admin" asp-controller="Category" asp-action="Index" >
                            <i class="bi bi-bookmarks-fill fa-lg"></i>
                            Thể loại truyện
                        </a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#collapseThree" data-bs-toggle="collapse"
                    aria-expanded="true" aria-controls="collapseThree">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Quản lý truyện</span>
                </a>
                <div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item @ManageNavPages.StoryNavClass(actionPage)" asp-area="Admin" asp-controller="Story" asp-action="Index" >
                            <i class="bi bi-book-fill fa-lg"></i>
                            Truyện
                        </a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item @ManageNavPages.UserNavClass(actionPage)">
                <a asp-area="Identity" asp-controller="User" asp-action="Index" class="nav-link" aria-controls="collapseUtilities">
                    <i class="fas fa-user fa-lg"></i>
                    <span>Quản lý người dùng</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Title -->
                    <h4 class="text-dark fw-semibold">@ViewData["Title"]</h4>
                    

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        @await Component.InvokeAsync(nameof(truyenchu.Components.Login))

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div id="page-content" class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_ErrorMessage.cshtml
@{
    var message = TempData["ErrorMessage"] as string;
}
@if (!String.IsNullOrEmpty(message))
{
    <div id="mytoast" data-bs-animation="true" data-bs-autohide="true" data-bs-delay="5000"  class="bg-danger mb-0 text-white fs-6 toast fade align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex align-items-center">
            <div class="toast-body">
                <i class="bi bi-check-lg"></i>
                @message
            </div>
            <button type="button" class="shadow-none btn-close ml-auto btn-close-white me-2 text-white" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>

    <script>
        var toast = new bootstrap.Toast(document.getElementById('mytoast'))
        toast.show()
    </script>
}

Views/Shared/_MenuManagePartial.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

@{
    var result = await authorizationService.AuthorizeAsync(User, "ViewManageMenu");
}

@if (result.Succeeded) {
  <div class="dropdown">
    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Manage
    </button>
    <ul class="dropdown-menu" style="z-index: 999999;">
        <li><h6 class="dropdown-header text-primary">Cơ sở dữ liệu</h6></li>
        <a class="dropdown-item" asp-area="Database" asp-controller="DatabaseManage" asp-action="Index">
            Database
        </a>
        <li><hr class="dropdown-divider"></li>
        <li><h6 class="dropdown-header text-primary">Liên hệ</h6></li>
        <a class="dropdown-item" asp-area="Contact" asp-controller="Contact" asp-action="Index">
            Quản lý liên hệ
        </a>
        <li><hr class="dropdown-divider"></li>
        <li><h6 class="dropdown-header text-primary">Người dùng</h6></li>
        <a class="dropdown-item" asp-area="Identity" asp-controller="Role" asp-action="Index">
            Quản lý role (vai trò)
        </a>
        <a class="dropdown-item" asp-area="Identity" asp-controller="User" asp-action="Index">
            Quản lý người dùng
        </a>
        <li><hr class="dropdown-divider"></li>
        <li><h6 class="dropdown-header text-primary">Tin tức</h6></li>
        <a class="dropdown-item" asp-area="Blog" asp-controller="Category" asp-action="Index">
            Quản lý chuyên mục Blog
        </a>
        <a class="dropdown-item" asp-area="Blog" asp-controller="Post" asp-action="Index">
            Quản lý bài viết Blog
        </a>
        <li><hr class="dropdown-divider"></li>
        <li><h6 class="dropdown-header text-primary">Sản phẩm</h6></li>
        <a class="dropdown-item" asp-area="Product" asp-controller="CategoryProduct" asp-action="Index">
            Quản lý loại sản phẩm
        </a>
        <a class="dropdown-item" asp-area="Product" asp-controller="Product" asp-action="Index">
           Quản lý sản phẩm
        </a>
        <li><hr class="dropdown-divider"></li>
        <li><h6 class="dropdown-header text-primary">File</h6></li>
        <a class="dropdown-item" target="_blank" asp-area="Files" asp-controller="FileManager" asp-action="Index">
            Quản lý files
        </a>
    </ul>
  </div>
}

Views/Shared/_MultiSelectScriptsPartial.cshtml
@model string
<link rel="stylesheet" href="~/css/multiple-select-custom.css">
<link rel="stylesheet" href="~/lib/multiple-select/multiple-select.min.css" />
<script src="~/lib/multiple-select/multiple-select.min.js"></script>

<script>
    $("@Model").multipleSelect({
        selectAll: false,
        keepOpen: false,
        isOpen: false,
    });
</script>

Views/Shared/_SearchStoryPartial.cshtml
<link href="~/lib/typeahead/style.css" rel="stylesheet">
<form method="get" asp-area="ViewStory" asp-controller="SearchStory" asp-action="SearchStory" id="navbar-search" class="d-flex">
    <input id="top-search" name="searchString"  class="typeahead form-control rounded-0 bg-dark" type="text" placeholder="Tìm kiếm ..." required>
    <button class="btn btn-outline-success rounded-0" type="submit">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>
    </button>
</form>

<script>
     // Select author
    var $input = $("#top-search");
    var api = "@Url.Action("SearchStoriesApi", "SearchStory")"+ "/?query=%QUERY";

    var engine = new Bloodhound({
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('storyName'),
        remote: {
            url: api,
            wildcard: '%QUERY',
        },
    });

    $('.typeahead').typeahead({
        hint: true,
        minLength: 1
    },
    {
        name: 'stories',
        display: 'storyName',
        source: engine.ttAdapter(),
        templates: {
            suggestion: function (result) {
                return `<div><a href="@Url.Action("DetailStory", "ViewStory", new {storySlug="replaceSlug"})">${result.storyName}</a></div>`.replace("replaceSlug", result.storySlug);
            }
        }
    })
</script>

Views/Shared/_StatusMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}
@if (!String.IsNullOrEmpty(message))
{
    <div id="mytoast" data-bs-animation="true" data-bs-autohide="true" data-bs-delay="5000"  class="bg-success mb-0 text-white fs-6 toast fade align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex align-items-center">
            <div class="toast-body">
                <i class="bi bi-check-lg"></i>
                @message
            </div>
            <button type="button" class="shadow-none btn-close ml-auto btn-close-white me-2 text-white" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>

    <script>
        var toast = new bootstrap.Toast(document.getElementById('mytoast'))
        toast.show()
    </script>
}